[platformio]
default_envs = esp32c3
src_dir = firmware/src
include_dir = firmware/include

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitc-02
framework = espidf
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = partitions.csv
board_build.embed_txtfiles = 

build_flags = 
    -O2 
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_LOG_DEFAULT_LEVEL=3

lib_deps =

monitor_filters = esp32_exception_decoder