#ifndef CONFIG_H
#define CONFIG_H

#include <cstdint>

#define FIRMWARE_VERSION "1.0.0"
#define HARDWARE_VERSION "1.0.0"
#define DEVICE_NAME "AetherLink"

// Battery Config
#define BATTERY_3S
#define BATTERY_4S
#define BATTERY_6S
#define BATTERY_8S
#define BATTERY_10S
#define BATTERY_12S
//ACTIVE CONFIG
#define BATTERY_CELL_COUNT BATTERY_4S

//VOLTAGE READING
#define ADC_RESOLUTION 12
#define ADC_REFERENCE_VOLTAGE 3.3f
#define ADC_MAX_VALUE 4095

// VOLT THRESHOolds
#define CELL_VOLTAGE_MAX 4.2f
#define CELL_VOLTAGE_MIN 2.5f
#define CELL_VOLTAGE_NOMINAL 3.7f

//pack V calc
#define PACK_VOLTAGE_MAX (CELL_VOLTAGE_MAX * BATTERY_CELL_COUNT)
#define PACK_VOLTAGE_MIN (CELL_VOLTAGE_MIN * BATTERY_CELL_COUNT)

//GPIO
#define ADC_PIN_CELL_1 GPIO_NUM_0
#define ADC_PIN_CELL_2 GPIO_NUM_1
#define ADC_PIN_CELL_3 GPIO_NUM_2
#define ADC_PIN_CELL_4 GPIO_NUM_3
#define ADC_PIN_CELL_5 GPIO_NUM_4
#define ADC_PIN_CELL_6 GPIO_NUM_5
#define ADC_PIN_CELL_7 GPIO_NUM_6
#define ADC_PIN_CELL_8 GPIO_NUM_7
#define ADC_PIN_CELL_9 GPIO_NUM_8
#define ADC_PIN_CELL_10 GPIO_NUM_9
#define ADC_PIN_CELL_11 GPIO_NUM_10
#define ADC_PIN_CELL_12 GPIO_NUM_11
//CURRENT SENors
#define I2C_SDA_PIN GPIO_NUM_12
#define I2C_SCL_PIN GPIO_NUM_13
#define I2C_FREQUENCY 100000

//STATS LED
#define STATS_LED_PIN GPIO_NUM_14

#define INA219_ADDRESS 0x40

//BLE

#define BLE_DEVICE_NAME "AetherLink"
#define BLE_TX_POWER 7 // dBm
//UID
#define BLE_SERVICE_UUID_PRIMARY \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF0,  \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF1
#define BLE_CHAR_UUID_BATTERY_STATUS \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF0,  \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF2
#define BLE_CHAR_UUID_CELL_VOLTAGES \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF0,  \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF3
#define BLE_CHAR_UUID_CURRENT \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF0,  \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF4
#define BLE_CHAR_UUID_SOC \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF0,  \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF5
#define BLE_CHAR_UUID_HEALTH \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF0,  \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF6
#define BLE_CHAR_UUID_SETTINGS \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF0,  \
    0x12, 0x34, 0x56, 0x78,  \
    0x9A, 0xBC, 0xDE, 0xF7

    // BLE PARAM
#define BLE_ADV_INTERVAL_MIN 32
#define BLE_ADV_INTERVAL_MAX 64

//Free rtos
//task stack sizes
#define BATTERY_TASK_STACK_SIZE 4096
#define BLE_TASK_STACK_SIZE 4096
#define STORAGE_TASK_STACK_SIZE 2048
#define LOGGER_TASK_STACK_SIZE 2048

//task priorities
#define BATTERY_TASK_PRIORITY 3
#define BLE_TASK_PRIORITY 2
#define STORAGE_TASK_PRIORITY 1
#define LOGGER_TASK_PRIORITY 1

//task delays
#define BATTERY_READ_INTERVAL 500
#define BLE_UPDATE_INTERVAL 1000
#define STORAGE_SYNC_INTERVAL 5000

//QUEUE CONFIG
#define BATTERY_QUEUE_SIZE 10
#define BLE_QUEUE_SIZE 20
#define STORAGE_QUEUE_SIZE 50
#define LOGGER_QUEUE_SIZE 100

//sotrage
//pariton
#define NVS_NAMESPACE_BATTERY "battery"
#define NVS_NAMESPACE_STATS "stats"
#define NVS_NAMESPACE_SETTINGS "settings"

//storage kays
#define NVS_KEY_BATTERY_UID "uid"
#define NVS_KEY_BATTERY_NAME "name"
#define NVS_KEY_BATTERY_CHARGE_CYCLE "charge_cycle"
#define NVS_KEY_BATTERY_DISCHARGE_CYCLE "discharge_cycle"
#define NVS_KEY_BATTERY_TOTAL_CAPACITY "total_capacity"
#define NVS_KEY_BATTERY_BATTERY_HEALTH "battery_health"

//calib thresh
//adc
#define ADC_CALIBRATION_FACTOR 1.0f
#define ADC_OFFSET 0.0f
//cur se
#define CURRENT_SENSOR_SENSITIVITY 0.04f // V/A
#define CURRENT_OFFSET 0.0f
//state is charge
#define SOC_MAX_CAPACITY 5000
#define SOC_INIT_PERCENTAGE 50
//BATTERY HEALTH THRESH
#define HEALTH_THRESHOLD_WARNING 80
#define HEALTH_THRESHOLD_CRITICAL 50

//logger

#define LOG_BUFFER_SIZE 1024
#define LOG_LEVEL_ERROR 1
#define LOG_LEVEL_WARN 2
#define LOG_LEVEL_INFO 3
#define LOG_LEVEL_DEBUG 4
#define LOG_LEVEL_VERBOSE 5
#define ACTIVE_LOG_LEVEL LOG_LEVEL_DEBUG

#define DEBUG_ENABLE 1
#define DEBUG_BATTERY_LOGIC 1
#define DEBUG_BLE_COMMS 1
#define DEBUG_STORAGE 1
#endif // CONFIG_H

